# Generated by Django 5.2.8 on 2025-12-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
